# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
